version: '3.8'

services:
  web:
    build: .
    command: bash -c "service rabbitmq-server start && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "15672:15672"
      - "5672:5672"
    environment:
      - DJANGO_SETTINGS_MODULE=calcy_final.settings
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ management console
